### ISSUE TITLE
崩溃报luajava.so找不到

### ISSUE THREAD

**Issue by ZZombiee** [liangchenhe55/Android-LuaJIT#1]
项目down下来，只看到luajava.c，运行直接挂了，怎么解决呢老哥

**Comment by ZZombiee** [comment]
好在解决了，你这个依赖过程需要clone你的原工程，make project生成so文件，然后把在compile你这个地址以后，再把so文件拉到jniLib下才行，否则会报找不到

**Comment by ichenhe** [comment]
应该是你的cpu架构比较特殊。我记得 jcenter 只上传了常用架构。
